import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import 'react-native-gesture-handler';
import MyDrawer from "./components/MyDrawer";


export const TOKEN = 'BEARER eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHMkpLblhwd2NZOGlSd3g1ZEZBXy00YlNoX1ZzRTE1NWVvN2JhSk9uYzBrIn0.eyJqdGkiOiI2NjFkY2I1YS1hZDA4LTQ0MTAtOTVmYy01M2ZkZmY5N2YzYWIiLCJleHAiOjE2MjcxMTkzMjksIm5iZiI6MCwiaWF0IjoxNjI3MDMyOTQ5LCJpc3MiOiJodHRwczovL2Rldi5ldW5zYS5iYS9hdXRoL3JlYWxtcy9pc3NzIiwiYXVkIjoiZnJvbnRlbmQiLCJzdWIiOiIzM2YwOTMxNC04MTlhLTRjZWItOGRiMC1jYzFmN2NhYWJmYTciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmcm9udGVuZCIsIm5vbmNlIjoiNmYwODI4NjEtMGM5Yi00NmU2LTgwMzEtZDM0ZDczNTU4MzI4IiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiZjNjMjE1NjUtNDM0My00MTc5LWEwMGQtZjFhMDQyZmIyNGQ5IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQiLCJuYW1lIjoixJBlbmFuYSBLdXN0dXJhIiwicHJlZmVycmVkX3VzZXJuYW1lIjoixJFrdXN0dXJhIiwiZ2l2ZW5fbmFtZSI6IsSQZW5hbmEiLCJmYW1pbHlfbmFtZSI6Ikt1c3R1cmEifQ.j-0mmiKXOnf9gkUtIDYoN-GG-S3RbepvI3qeV0FDF-hOFEfilAKeKmngijt3ddGR6ipBAuaTeaIXLpgaRyEGV1QOEmsajok0sd6mouzZIPuDjhGC6Io4yCTHaNnyPSVwTeQ3Gd6VPl83gXAAfhlMc5VPRYqGCYX55sRwyEEofBsLA4ulOpWVybaHiuhwFOX6c6plqRcOoYpTZBWAexbVxpLNza159iRdE1cQxpVha1l3MJOM3CZYw9HLs9nX0LUbkivGJoJgZ2dfXHCpV1FIEun69BsNEmPrjDShEiuN7S85URV_in46ljKrDvbZfrIYFz6-W_BCdGwZHU2NqOQ00Q'


export default function App() {
    return (

        <NavigationContainer>
            <MyDrawer />
        </NavigationContainer>

    );
}


