import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import 'react-native-gesture-handler';
import MyDrawer from "./components/MyDrawer";


export const TOKEN = 'BEARER eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHMkpLblhwd2NZOGlSd3g1ZEZBXy00YlNoX1ZzRTE1NWVvN2JhSk9uYzBrIn0.eyJqdGkiOiI5ZjExMmRiOC04YTE2LTRiNDMtYjhkOC1kYWE2ZWQ3YTY2NzkiLCJleHAiOjE2MjgzMjc3MTIsIm5iZiI6MCwiaWF0IjoxNjI4MjQxNDcyLCJpc3MiOiJodHRwczovL2Rldi5ldW5zYS5iYS9hdXRoL3JlYWxtcy9pc3NzIiwiYXVkIjoiZnJvbnRlbmQiLCJzdWIiOiIzM2YwOTMxNC04MTlhLTRjZWItOGRiMC1jYzFmN2NhYWJmYTciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmcm9udGVuZCIsIm5vbmNlIjoiNmZmZGY1ZmUtZjc3YS00NDQxLWJkODItMjYzNjNiYzljY2UzIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiODAxM2IyMzAtZjg4My00ODVhLTlkOGMtM2UxZjNiY2ZhNTgwIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQiLCJuYW1lIjoixJBlbmFuYSBLdXN0dXJhIiwicHJlZmVycmVkX3VzZXJuYW1lIjoixJFrdXN0dXJhIiwiZ2l2ZW5fbmFtZSI6IsSQZW5hbmEiLCJmYW1pbHlfbmFtZSI6Ikt1c3R1cmEifQ.Q8UFVt1HkRejNdvke5XfZj7dbI0VoqHD_SHatYeje2q9fSY89IGTAch6vHC3FNHMeW4It5K92PZR7YVHnFh5v-x0eVVCvUy00rILkiRNUKtQ6HGifMRr_zgkMxFduEytgJJK8ecTKlbeMKcjwMyiRO1jd0rcK8cd5VoVJEnZPYicPbSj83fbUMBFlIbt7h-HexeNsE6hzwsgwitrVHez-4oGEquh-vikqB1xqOd86PNw0yNl6pyvEvxziaeid-KctNFtiNuXkppEa4efIsn1DhsmfFgDEuwprTqtrEBQC7PGkP197inzUWl8m-AYleWu9JEdWiTfLZsikc9rzBBVvw'


export default function App() {
    return (

        <NavigationContainer>
            <MyDrawer />
        </NavigationContainer>

    );
}


